"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Download, RefreshCw, Share2, Swords, UsersRound } from "lucide-react";
import { Ability } from "../../lib/ability";
import { buildCompatibility, Compatibility, SharedProfile } from "../../lib/compatibility";
import { Diagnosis } from "../../lib/types";

const labels: Record<string, string> = { attack: "攻撃力", defense: "防御力", versatility: "汎用性", difficulty: "難易度", growth: "成長性" };
const shareId = (value: string) => value.trim().match(/(?:\/share\/)?([0-9a-f-]{36})\/?$/i)?.[1] ?? null;

export default function AbilityPage() {
  const [ability, setAbility] = useState<Ability | null>(null); const [error, setError] = useState(false); const [shareMessage, setShareMessage] = useState("");
  const [coOp, setCoOp] = useState(false); const [friendUrl, setFriendUrl] = useState(""); const [friend, setFriend] = useState<SharedProfile | null>(null); const [compatibility, setCompatibility] = useState<Compatibility | null>(null); const [coOpError, setCoOpError] = useState(""); const [loading, setLoading] = useState(false);
  const generate = async () => { setError(false); const raw = sessionStorage.getItem("orbital-result"); if (!raw) return; try { const response = await fetch("/api/generate-ability", { method: "POST", headers: { "Content-Type": "application/json" }, body: raw }); if (!response.ok) throw new Error(); const data = await response.json(); setAbility(data.ability); sessionStorage.setItem("orbital-ability", JSON.stringify(data.ability)); } catch { setError(true); } };
  const download = () => { if (!ability) return; const canvas = document.createElement("canvas"); canvas.width = 1080; canvas.height = 1350; const context = canvas.getContext("2d")!; const gradient = context.createLinearGradient(0, 0, 1080, 1350); gradient.addColorStop(0, "#0e1636"); gradient.addColorStop(1, "#080a18"); context.fillStyle = gradient; context.fillRect(0, 0, 1080, 1350); context.strokeStyle = "#55e6db"; context.lineWidth = 3; context.strokeRect(65, 65, 950, 1220); context.fillStyle = "#55e6db"; context.font = "500 30px sans-serif"; context.fillText("ORBITAL / PERSONAL ABILITY CARD", 110, 150); context.fillStyle = "#fff"; context.font = "900 88px sans-serif"; context.fillText(ability.type, 110, 300); context.fillStyle = "#9c78ff"; context.font = "700 52px sans-serif"; context.fillText(ability.abilityName, 110, 410); context.fillStyle = "#cbd5f1"; context.font = "34px sans-serif"; context.fillText(ability.shortDescription.slice(0, 30), 110, 490); let y = 620; context.font = "500 36px sans-serif"; Object.entries(ability.rating).forEach(([key, value]) => { context.fillStyle = "#cbd5f1"; context.fillText(labels[key], 110, y); context.fillStyle = "#55e6db"; context.fillRect(340, y - 28, value * 5, 22); context.fillStyle = "#fff"; context.fillText(String(value), 880, y); y += 95; }); context.fillStyle = "#9ba8c7"; context.font = "28px sans-serif"; context.fillText("ORBITAL — PERSONAL ABILITY CARD", 110, 1180); const link = document.createElement("a"); link.href = canvas.toDataURL("image/png"); link.download = "orbital-ability-card.png"; link.click(); };
  const share = async () => { if (!ability) return; const raw = sessionStorage.getItem("orbital-result"); if (!raw) return; setShareMessage(""); try { const response = await fetch("/api/share", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ diagnosis: JSON.parse(raw), ability }) }); const data = await response.json(); if (!data.id) throw new Error(data.error); await navigator.clipboard.writeText(`${location.origin}/share/${data.id}`); setShareMessage("共有URLをコピーしました。友達に送ると共闘診断に使えます。"); } catch (cause) { setShareMessage(cause instanceof Error ? cause.message : "共有URLを作成できませんでした。"); } };
  const diagnoseCoOp = async (event: FormEvent) => { event.preventDefault(); const id = shareId(friendUrl); const raw = sessionStorage.getItem("orbital-result"); if (!id) return setCoOpError("友達の共有URLをそのまま貼り付けてください。"); if (!raw || !ability) return setCoOpError("あなた自身の診断と能力生成を完了してください。"); setLoading(true); setCoOpError(""); try { const response = await fetch(`/api/share?id=${id}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); const mine: SharedProfile = { mainType: (JSON.parse(raw) as Diagnosis).mainType, scores: (JSON.parse(raw) as Diagnosis).scores, ability }; setFriend(data); setCompatibility(buildCompatibility(mine, data)); } catch (cause) { setCoOpError(cause instanceof Error ? cause.message : "相性を測定できませんでした。"); } finally { setLoading(false); } };
  useEffect(() => { const saved = sessionStorage.getItem("orbital-ability"); if (saved) setAbility(JSON.parse(saved)); else generate(); }, []);
  if (!ability) return <main className="shell hero"><div className="eyebrow">GENERATING YOUR ABILITY</div><h1>{error ? "生成に失敗しました" : "能力を設計中…"}</h1><button className="btn" onClick={generate}>{error ? "もう一度試す" : "少々お待ちください"}</button></main>;
  if (coOp) return <main className="shell"><nav className="nav"><Link className="logo" href="/">ORBITAL</Link><button className="btn secondary" onClick={() => setCoOp(false)}>能力詳細に戻る</button></nav><section className="result-head"><div className="eyebrow">TWO PERSON SYNERGY</div><h1 className="ability-name">共闘適性診断</h1><p className="muted">友達の共有URLを読み込み、2人の役割と連携技を測定します。</p></section><section className="card"><div className="label">YOUR STATUS</div><p><b>{ability.type}</b> ／ {ability.abilityName}</p></section><form className="card co-op-form" onSubmit={diagnoseCoOp}><label className="label" htmlFor="friend-url">FRIEND&apos;S SHARE URL</label><input id="friend-url" value={friendUrl} onChange={(event) => setFriendUrl(event.target.value)} placeholder="https://…/share/xxxxxxxx" /><button className="btn" disabled={loading}><UsersRound size={18} />{loading ? "測定中…" : "相性を測定する"}</button>{coOpError && <p className="form-error">{coOpError}</p>}</form>{compatibility && friend && <section className="co-op-result"><div className="compatibility-score"><span>COMPATIBILITY</span><b>{compatibility.score}%</b><strong>GRADE {compatibility.grade}</strong></div><div className="grid two"><article className="card"><div className="label">TEAM STYLE</div><h2>{compatibility.style}</h2><p className="muted">{compatibility.summary}</p></article><article className="card"><div className="label">YOUR ROLES</div><p><b>あなた：</b>{compatibility.roles[0]}</p><p><b>友達：</b>{compatibility.roles[1]}</p></article></div><article className="card"><div className="label"><Swords size={14} /> COMBO MOVE</div><h2>二重軌道・共鳴連携</h2><p>{compatibility.combo}</p></article><article className="card"><div className="label">FRIEND PROFILE</div><p><b>{friend.mainType}</b> ／ {friend.ability.abilityName}</p><p className="muted">{friend.ability.shortDescription}</p></article></section>}</main>;
  return <main className="shell"><nav className="nav"><Link className="logo" href="/">ORBITAL</Link><span className="pill">YOUR ABILITY</span></nav><section className="result-head"><div className="eyebrow">{ability.type}</div><h1 className="ability-name">{ability.abilityName}</h1><p className="muted">{ability.shortDescription}</p></section><section className="card"><div className="label">ABILITY PROFILE</div><p style={{ lineHeight: 1.9 }}>{ability.description}</p><div className="grid two"><div><div className="label">発動条件</div><p>{ability.activation}</p></div><div><div className="label">制約・誓約</div><p>{ability.restriction}<br />{ability.oath}</p></div></div><div className="label">弱点</div><p>{ability.weakness}</p></section><section className="card"><div className="label">STATUS</div>{Object.entries(ability.rating).map(([key, value]) => <div className="stat" key={key}><span>{labels[key]}</span><span className="bar"><i style={{ width: `${value}%` }} /></span><b>{value}</b></div>)}</section><section className="card ability-card-guide"><div className="label">ABILITY CARD IMAGE</div><h2>能力カードを保存・共有</h2><p className="muted">名前、タイプ、能力値を1080×1350の縦長PNGカードにして保存できます。</p></section><div className="grid two"><button className="btn" onClick={download}><Download size={17} />能力カードをPNG保存</button><button className="btn secondary" onClick={generate}><RefreshCw size={17} />能力を再生成</button></div><button className="btn secondary" style={{ width: "100%" }} onClick={share}><Share2 size={17} />共有URLをコピー</button>{shareMessage && <p className="share-message">{shareMessage}</p>}<button className="btn co-op-link" onClick={() => setCoOp(true)}><UsersRound size={18} />友達との相性・共闘診断へ</button></main>;
}
